init_config:

instances:

    ## @param prometheus_url - string - required
    ## The URL where your application metrics are exposed by Prometheus.
    #
  - prometheus_url: http://api-gateway:8080/actuator/prometheus

    ## @param namespace - string - required
    ## The namespace to be appended before all metrics namespace
    #
    namespace: 'pm'

    ## @param metrics - list of key:value elements - required
    ## List of `<METRIC_TO_FETCH>: <NEW_METRIC_NAME>` for metrics to be fetched from the prometheus endpoint.
    ## <NEW_METRIC_NAME> is optional. It transforms the name in Datadog if set.
    ## This list should contain at least one metric
    #
    metrics:
      - http*
      - jvm*
      - tomcat*
